import assert from 'node:assert/strict';
const base=process.argv[2]||'http://localhost:5173';
const post=async(op,value,extra={})=>{const r=await fetch(base+'/api/diary',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({op,value,...extra})});const data=await r.json();assert.equal(r.status,200,JSON.stringify(data));return data};
const get=async()=>await(await fetch(base+'/api/diary')).json();
const id='qa-'+Date.now(),tid=id+'-task';
const p={id,title:'QA 전용 계획',start_date:'2026-09-01',end_date:'2026-09-27',priority:2,success:'QA',estimate:60,improvement:''};
let d=await post('plan-create',p);
d=await post('plan-edit',{...p,title:'QA 수정',version:1});
assert.equal(JSON.parse(d.plan_revisions.find(r=>r.plan_id===id&&r.version===1).snapshot).title,p.title);
assert.equal(d.plan_revisions.filter(r=>r.plan_id===id).length,2);
const t={id:tid,plan_id:id,title:'<script>alert("QA")</script>',due_date:'2026-09-01',priority:1,tags:'검증',estimate:60};
await post('task-create',t);
const log={id:id+'-record',task_id:tid,start_at:'2026-09-01T00:00:00.000Z',end_at:'2026-09-01T00:30:00.000Z',blocked:'재료 부족',note:'QA 전용',complete:true,cycle:0};
await Promise.all([post('execution',log),post('execution',log),post('execution',{...log,id:id+'-other-request'})]);
d=await get();assert.equal(d.executions.filter(e=>e.task_id===tid).length,1);assert.equal(d.completions.filter(c=>c.task_id===tid).length,1);assert.equal(d.tasks.find(t=>t.id===tid).status,'done');assert.equal(d.tasks.find(t=>t.id===tid).estimate,60);assert.equal(d.plans.find(p=>p.id===id).estimate,60);
const stable=await get();assert.deepEqual(d,stable);
await post('task-reopen',null,{id:tid});await post('task-reopen',null,{id:tid});d=await get();assert.equal(d.tasks.find(t=>t.id===tid).cycle,1);assert.equal(d.tasks.find(t=>t.id===tid).status,'open');
await post('execution',log);d=await get();assert.equal(d.tasks.find(t=>t.id===tid).status,'open');assert.equal(d.executions.filter(e=>e.task_id===tid).length,1);
await post('execution',{...log,id:id+'-record2',cycle:1,complete:false});
await post('execution',{...log,id:id+'-record3',cycle:1,complete:false});
await post('task-edit',{...t,title:'QA 수정 할 일',priority:3});
const next={...p,id:id+'-next',title:'QA 다음 계획'};
await post('review',{id:id+'-review',plan_id:id,start_date:p.start_date,end_date:p.end_date,improvement:'재료 먼저 모으기',next});
d=await get();assert.equal(d.plans.find(p=>p.id===next.id).improvement,'재료 먼저 모으기');assert.equal(d.reviews.find(r=>r.plan_id===id).next_plan_id,next.id);
const invalid=await fetch(base+'/api/diary',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({op:'execution',value:{...log,id:id+'invalid',start_at:log.end_at,end_at:log.start_at}})});assert.equal(invalid.status,400);
const csrf=await fetch(base+'/api/diary',{method:'POST',headers:{'Content-Type':'application/json',Origin:'https://unrelated.invalid'},body:'{"op":"bootstrap"}'});assert.equal(csrf.status,403);
await post('task-delete',null,{id:tid});d=await get();assert.ok(d.tasks.find(t=>t.id===tid).deleted_at);assert.equal(d.executions.filter(e=>e.task_id===tid).length,3);
console.log(JSON.stringify({status:'PASS',testPlan:id,checks:['plan history','concurrent completion deduplication (same and different request IDs)','unchanged plan and estimate','reload identity equality','reopen idempotency','stale completion rejection','3 execution records','edit and soft delete','review carry-forward','invalid time rejection','cross-origin mutation rejection']}));
