import assert from 'node:assert/strict';
import fs from 'node:fs';
import {DatabaseSync} from 'node:sqlite';
const base=process.env.TEST_BASE||'http://localhost:5173',out=process.env.EVIDENCE_DIR||'work/t07-evidence';fs.mkdirSync(out,{recursive:true});
const password=crypto.randomUUID()+'x',newPassword=crypto.randomUUID()+'y',run=Date.now().toString(36),evidence=[];
function redact(x){if(typeof x==='string')return x.replaceAll(password,'[비밀번호 가림]').replaceAll(newPassword,'[비밀번호 가림]').replace(/pds_session=[a-f0-9]{64}/g,'pds_session=[세션 가림]');if(Array.isArray(x))return x.map(redact);if(x&&typeof x==='object')return Object.fromEntries(Object.entries(x).map(([k,v])=>[k,/password/i.test(k)?'[비밀번호 가림]':redact(v)]));return x}
async function req(label,path='/api/diary',body,session='',expected=200,extra={}){const method=body?'POST':'GET',headers={...(body?{'Content-Type':'application/json',Origin:base}:{}),...(session?{Cookie:session}:{}),...extra};const r=await fetch(base+path,{method,headers,body:body?JSON.stringify(body):undefined,redirect:'manual'});const text=await r.text();let data;try{data=JSON.parse(text)}catch{data={html:text.slice(0,180)}}evidence.push({label,request:{method,url:path,headers:redact(headers),body:redact(body)},response:{status:r.status,body:redact(data),setCookie:redact(r.headers.get('set-cookie'))}});assert.equal(r.status,expected,`${label}: ${JSON.stringify(data)}`);assert.ok(!text.includes(password)&&!text.includes(newPassword),'password leaked');return {data,cookie:r.headers.get('set-cookie')?.split(';')[0]||session}}
await req('공개 로그인 화면','/',undefined,'',200);await req('비로그인 자료 화면','/diary',undefined,'',307);await req('비로그인 직접 API','/api/diary',undefined,'',401);
const users=[];for(const label of ['a','b']){const username='t07_'+run+label;const sign=await req('가입 '+label,'/api/auth',{action:'signup',username,password},'',201);assert.ok(evidence.at(-1).response.setCookie.includes('HttpOnly'));users.push({username,cookie:sign.cookie,label});}
await req('중복 가입','/api/auth',{action:'signup',username:users[0].username,password},'',409);
const wrong=await req('잘못된 비밀번호','/api/auth',{action:'login',username:users[0].username,password:newPassword},'',401);const absent=await req('없는 아이디','/api/auth',{action:'login',username:'missing_'+run,password:newPassword},'',401);assert.deepEqual(wrong.data,absent.data);
if(base.startsWith('http://localhost')){const files=fs.readdirSync('.wrangler/state/v3/d1/miniflare-D1DatabaseObject').filter(s=>s.endsWith('.sqlite')&&s!=='metadata.sqlite');const db=new DatabaseSync('.wrangler/state/v3/d1/miniflare-D1DatabaseObject/'+files[0],{readOnly:true});const hashes=users.map(u=>db.prepare('SELECT username,password_hash FROM auth_users WHERE username=?').get(u.username));assert.notEqual(hashes[0].password_hash,hashes[1].password_hash);assert.ok(hashes.every(h=>h.password_hash.startsWith('$2b$12$')&&!h.password_hash.includes(password)));fs.writeFileSync(out+'/password-hashes.json',JSON.stringify({environment:'local temporary test accounts; not user accounts',algorithm:'bcrypt',library:'bcryptjs 3.0.3',cost:12,sameInput:true,rows:hashes},null,2));db.close();}
for(const u of users){u.plan={id:crypto.randomUUID(),title:'검증 계획 '+u.label,start_date:'2026-09-15',end_date:'2026-09-20',priority:2,success:'격리 확인',estimate:30};await req('내 계획 만들기 '+u.label,undefined,{op:'plan-create',value:u.plan},u.cookie);u.task={id:crypto.randomUUID(),plan_id:u.plan.id,title:'검증 할 일 '+u.label,due_date:'2026-09-15',priority:2,tags:'검증',estimate:10};await req('내 할 일 만들기 '+u.label,undefined,{op:'task-create',value:u.task},u.cookie);await req('내 자료 읽기 '+u.label,'/api/diary?id='+u.task.id,undefined,u.cookie);await req('내 자료 수정 '+u.label,undefined,{op:'task-edit',value:{...u.task,title:'검증 수정 '+u.label}},u.cookie);u.baseline=(await req('공격 전 자료 '+u.label,undefined,undefined,u.cookie)).data;}
for(let i=0;i<2;i++){const u=users[i],other=users[1-i];await req(`${u.label}→${other.label} 읽기 거절`,'/api/diary?id='+other.task.id,undefined,u.cookie,404);await req(`${u.label}→${other.label} 수정 거절`,undefined,{op:'task-edit',value:{...other.task,title:'침입 수정'}},u.cookie,404);await req(`${u.label}→${other.label} 삭제 거절`,undefined,{op:'task-delete',id:other.task.id},u.cookie,404);await req(`${u.label}→${other.label} 하위 생성 거절`,undefined,{op:'task-create',value:{...other.task,id:crypto.randomUUID()}},u.cookie,404);await req(`${u.label}→${other.label} 계획 수정 거절`,undefined,{op:'plan-edit',value:{...other.plan,version:1}},u.cookie,404);await req(`${u.label}→${other.label} 실행 생성 거절`,undefined,{op:'execution',value:{id:crypto.randomUUID(),task_id:other.task.id}},u.cookie,404);
const forged=await req('주소·헤더 소유자 위조 '+u.label,'/api/diary?user_id='+other.username,undefined,u.cookie,200,{'X-User-Id':other.username,'oai-authenticated-user-id':other.username});assert.deepEqual(forged.data,u.baseline);
const forgedBody=await req('본문 소유자 위조 '+u.label,undefined,{op:'bootstrap',user_id:other.username,owner_id:other.username},u.cookie);assert.deepEqual(forgedBody.data,u.baseline);}
for(const u of users){const after=await req('공격 후 자료 '+u.label,undefined,undefined,u.cookie);assert.deepEqual(after.data,u.baseline);await req('외부 Origin 거절 '+u.label,undefined,{op:'bootstrap'},u.cookie,403,{Origin:'https://unrelated.invalid'});const exp=await req('전체 내보내기 '+u.label,'/api/export',undefined,u.cookie);assert.equal(exp.data.plans.length,1);assert.equal(exp.data.tasks.length,1);}
const a=users[0];await req('로그아웃 전 같은 요청','/api/diary',undefined,a.cookie);await req('로그아웃','/api/auth',{action:'logout'},a.cookie);await req('로그아웃 후 같은 값·같은 요청','/api/diary',undefined,a.cookie,401);
a.cookie=(await req('다시 로그인','/api/auth',{action:'login',username:a.username,password})).cookie;const old=a.cookie;await req('비밀번호 변경 전','/api/diary',undefined,old);await req('비밀번호 변경','/api/auth',{action:'password',currentPassword:password,newPassword},old);await req('비밀번호 변경 후 기존 세션','/api/diary',undefined,old,401);await req('이전 비밀번호 거절','/api/auth',{action:'login',username:a.username,password},'',401);a.cookie=(await req('새 비밀번호 로그인','/api/auth',{action:'login',username:a.username,password:newPassword})).cookie;
for(const u of users){await req('내 자료 삭제 '+u.label,undefined,{op:'task-delete',id:u.task.id},u.cookie);await req('계정 삭제 '+u.label,'/api/auth',{action:'delete',currentPassword:u===a?newPassword:password},u.cookie);await req('삭제 계정 세션 거절 '+u.label,undefined,undefined,u.cookie,401);}
const serialized=JSON.stringify({checked_at:new Date().toISOString(),base,note:'실제 요청·응답. 임시 테스트 계정은 종료 시 삭제. 세션값·비밀번호는 기록 전에 가림.',checks:evidence},null,2);assert.ok(!serialized.includes(password)&&!serialized.includes(newPassword));fs.writeFileSync(out+'/http-evidence.json',serialized);console.log('PASS: '+evidence.length+' HTTP checks; two-way isolation, sessions, password change, deletion, export.');
