'use client';
import {useState,useEffect,FormEvent} from 'react';
const defaults={question:'계획을 작게 나누면 하루에 완료하는 항목 수가 늘어날까?',metric:'완료한 계획 항목 수',unit:'개',rule:'플레이 전에 오늘 할 항목을 최대 5개 정한다.',calculation:'그날 완료한 항목의 수를 정수로 기록. 같은 항목은 하루 한 번만 계산.',missing:'기록하지 않은 날은 0으로 만들지 않고 관찰일에서 제외한다. 실제 0개 완료는 0으로 기록한다.',duplicate:'같은 날짜는 한 번만 기록하고, 같은 항목은 하루 한 번만 센다.',outlier:'큰 값도 실제 값이면 유지하며, 이유를 일일 메모에 적는다.',rounding:'일일 값과 합계는 정수, 평균만 소수 셋째 자리에서 반올림해 둘째 자리까지 표시한다.',weekStart:'월요일'};
const blankConfig={...defaults,question:'',rule:''};
const labels:Record<string,string>={metric:'지표',unit:'단위',calculation:'계산 방법',question:'관찰 질문',rule:'변경 전 계획 규칙',missing:'값이 빠졌을 때',duplicate:'중복 처리',outlier:'유난히 큰 값 처리',rounding:'반올림',weekStart:'주 시작 요일'};
export default function Observation(){const [data,setData]=useState<any>(null),[config,setConfig]=useState(defaults),[error,setError]=useState(''),[busy,setBusy]=useState(false);
useEffect(()=>{fetch('/api/observation').then(r=>r.json()).then((d:any)=>{if(d.error)setError(d.error);else {setData(d);if(d.canRestore)setConfig(blankConfig)}}).catch(()=>setError('관찰 기록을 불러오지 못했어요.'))},[]);
async function send(body:any){setBusy(true);setError('');try{const r=await fetch('/api/observation',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d:any=await r.json();if(!r.ok)throw Error(d.error);setData(d);if(body.action==='reset')setConfig(blankConfig)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
function day(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);void send({action:'day',value:Number(f.get('value')),note:f.get('note')})}
function change(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);void send({action:'change',rule:f.get('rule'),reason:f.get('reason')})}
return <details className="observation-panel"><summary>5일 관찰 <span>{data?.days?.length||0} / 5일</span></summary><div className="account-content">{error&&<p className="error" role="alert">{error}</p>}{!data?<p>{error?'잠시 뒤 페이지를 새로고침해 주세요.':'기록을 불러오고 있어요.'}</p>:!data.setup?<form onSubmit={e=>{e.preventDefault();void send({action:'start',config})}}><h2>이번에는 어떻게 계획해 볼까요?</h2>{data.canRestore&&<p role="status">입력한 관찰 내용을 비웠어요. 새로 적어 주세요. <button type="button" disabled={busy} onClick={()=>send({action:'restore'})}>초기화 되돌리기</button></p>}<p>아래는 제안이에요. 내 질문과 계획에 맞게 고친 뒤 시작해 주세요. 시작 후 비교 기준은 고정돼요.</p>{Object.keys(defaults).filter(k=>!['metric','unit','calculation'].includes(k)).map(k=><label key={k}>{labels[k]}<textarea required value={(config as any)[k]} onChange={e=>setConfig({...config,[k]:e.target.value})}/></label>)}<p><strong>지표: {config.metric} · 단위: 개</strong><br/>{config.calculation}</p><button className="primary" disabled={busy}>이 기준으로 관찰 시작</button></form>:<>{<button type="button" disabled={busy} onClick={()=>send({action:'reset'})}>입력 내용 초기화</button>}<h2>{data.setup.config.question}</h2><p>지표 · {data.setup.config.metric} ({data.setup.config.unit})</p><p>현재 규칙 · {data.setup.change?.rule||data.setup.config.rule}</p><details><summary>고정한 계산 규칙 보기</summary>{Object.entries(data.setup.config).map(([k,v])=><p key={k}>{labels[k]||k}: {String(v)}</p>)}</details><p role="status">{data.complete?'5일 기록 완료':`${data.recordedDays} / 5일 기록 · 현재까지의 중간 집계예요.`}</p><div className="observation-totals"><strong>합계 {data.sum}개</strong><strong>평균 {data.average??'—'}개</strong><span>변경 전 {data.before??'—'}개 / 변경 후 {data.after??'—'}개</span></div><ol>{data.days.map((d:any,i:number)=><li key={d.id}><strong>{i+1}일차 · {d.day} · {d.value}개</strong><p>{d.note}</p><small>기록 시각 {new Date(d.created_at).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'})}</small>{i===1&&data.setup.change&&<section className="carry"><strong>계획 규칙 변경</strong><p>{data.setup.change.previous_rule} → {data.setup.change.rule}</p><p>이유: {data.setup.change.reason}</p><small>{new Date(data.setup.change.changed_at).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'})} · 근거: {data.setup.change.based_on.map((d:any)=>d.day).join(', ')}</small></section>}</li>)}</ol>{data.days.length===2&&!data.setup.change?<form onSubmit={change}><h3>3일차 전에 규칙 하나 바꾸기</h3><label>새 계획 규칙 하나<textarea name="rule" required placeholder="예: 오늘 할 항목을 최대 3개로 줄인다."/></label><label>1·2일차를 보고 바꾸는 이유<textarea name="reason" required/></label><button disabled={busy}>변경 시각과 근거 남기기</button></form>:data.days.length<5?<form onSubmit={day}><h3>오늘의 실제 기록</h3><p>서울 기준 오늘 날짜로 저장해요. 실제로 완료한 값만 적어 주세요.</p><label>오늘 완료한 항목 수 · 개<input name="value" type="number" min={0} max={10000} step={1} required/></label><label>완료한 항목과 돌아보기<textarea name="note" required maxLength={1000}/></label><button disabled={busy} className="primary">오늘 기록 저장</button></form>:<p>5일 기록을 모두 남겼어요. 내보내기로 합계·평균과 근거를 함께 확인해 주세요.</p>}</>}</div></details>}
