import {sqliteTable,text,integer,index,uniqueIndex} from 'drizzle-orm/sqlite-core';
export const plans=sqliteTable('plans',{id:text('id').primaryKey(),ownerId:text('owner_id'),mergedInto:text('merged_into'),title:text('title').notNull(),startDate:text('start_date').notNull(),endDate:text('end_date').notNull(),priority:integer('priority').notNull(),success:text('success').notNull(),estimate:integer('estimate').notNull(),improvement:text('improvement').notNull().default(''),version:integer('version').notNull().default(1),createdAt:text('created_at').notNull()});
export const revisions=sqliteTable('plan_revisions',{id:text('id').primaryKey(),planId:text('plan_id').notNull().references(()=>plans.id),version:integer('version').notNull(),snapshot:text('snapshot').notNull(),createdAt:text('created_at').notNull()},t=>[uniqueIndex('revision_plan_version').on(t.planId,t.version)]);
export const tasks=sqliteTable('tasks',{id:text('id').primaryKey(),planId:text('plan_id').notNull().references(()=>plans.id),title:text('title').notNull(),dueDate:text('due_date').notNull(),priority:integer('priority').notNull(),tags:text('tags').notNull().default(''),estimate:integer('estimate').notNull(),status:text('status').notNull().default('open'),cycle:integer('cycle').notNull().default(0),deletedAt:text('deleted_at'),createdAt:text('created_at').notNull()},t=>[index('tasks_plan_due').on(t.planId,t.dueDate)]);
export const executions=sqliteTable('executions',{id:text('id').primaryKey(),taskId:text('task_id').notNull().references(()=>tasks.id),startAt:text('start_at').notNull(),endAt:text('end_at').notNull(),minutes:integer('minutes').notNull(),blocked:text('blocked').notNull().default(''),note:text('note').notNull().default(''),completionKey:text('completion_key'),createdAt:text('created_at').notNull()},t=>[index('executions_task').on(t.taskId),uniqueIndex('execution_completion_key').on(t.completionKey)]);
export const completions=sqliteTable('completions',{id:text('id').primaryKey(),taskId:text('task_id').notNull().references(()=>tasks.id),cycle:integer('cycle').notNull(),createdAt:text('created_at').notNull()},t=>[uniqueIndex('completion_task_cycle').on(t.taskId,t.cycle)]);
export const reviews=sqliteTable('reviews',{id:text('id').primaryKey(),planId:text('plan_id').notNull().references(()=>plans.id),startDate:text('start_date').notNull(),endDate:text('end_date').notNull(),improvement:text('improvement').notNull(),nextPlanId:text('next_plan_id').notNull().references(()=>plans.id),createdAt:text('created_at').notNull()});

export const authUsers=sqliteTable('auth_users',{id:text('id').primaryKey(),username:text('username').notNull().unique(),passwordHash:text('password_hash').notNull(),sessionEpoch:integer('session_epoch').notNull().default(0),createdAt:text('created_at').notNull()});
export const authSessions=sqliteTable('auth_sessions',{tokenHash:text('token_hash').primaryKey(),userId:text('user_id').notNull().references(()=>authUsers.id),expiresAt:text('expires_at').notNull()},t=>[index('session_user').on(t.userId)]);
export const authAttempts=sqliteTable('auth_attempts',{id:text('id').primaryKey(),count:integer('count').notNull()});
export const observations=sqliteTable('observations',{userId:text('user_id').primaryKey().references(()=>authUsers.id),config:text('config').notNull(),createdAt:text('created_at').notNull(),change:text('change')});
export const observationDays=sqliteTable('observation_days',{id:text('id').primaryKey(),userId:text('user_id').notNull().references(()=>authUsers.id),day:text('day').notNull(),value:integer('value').notNull(),note:text('note').notNull(),createdAt:text('created_at').notNull()},t=>[uniqueIndex('observation_user_day').on(t.userId,t.day)]);
